# Generated by Django 4.2.10 on 2024-05-17 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programacion_labor', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tractor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tractor',
            name='idusuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='reportetractor',
            name='idprogramacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programacion_labor.programacion'),
        ),
        migrations.AddField(
            model_name='reportetractor',
            name='idusuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
