# Generated by Django 4.2.10 on 2024-04-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tractor', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipotractor',
            name='TipoTractor',
            field=models.CharField(max_length=100, unique=True, verbose_name='Tipo de tractor'),
        ),
    ]
