# Generated by Django 5.0.3 on 2024-04-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tractor', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportetractor',
            name='correlativo',
            field=models.IntegerField(unique=True, verbose_name='Correlativo'),
        ),
    ]
