# Generated by Django 4.2.10 on 2024-06-28 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tractor', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TractorSupervisor',
            fields=[
                ('idtractorsupervisor', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('fechaInicio', models.DateField(auto_now=True, verbose_name='Fecha Inicio')),
                ('fechaFin', models.DateField(verbose_name='Fecha Fin')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('idsupervisor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('idtractor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='tractor.tractor', verbose_name='Tractor')),
            ],
            options={
                'verbose_name': 'tractor por supervisor',
                'verbose_name_plural': 'tractores por supervisores',
            },
        ),
    ]
