# Generated by Django 4.2.10 on 2024-04-24 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tractor', '0003_alter_tipotractor_tipotractor'),
        ('tractor', '0003_remove_tractor_idcultivo_tractor_idfundo'),
    ]

    operations = [
    ]
