# Generated by Django 4.2.10 on 2024-06-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tractor', '0003_tractorsupervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tractorsupervisor',
            name='fechaInicio',
            field=models.DateField(verbose_name='Fecha Inicio'),
        ),
    ]
