# Generated by Django 4.2.10 on 2024-06-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tractor', '0004_alter_tractorsupervisor_fechainicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tractorsupervisor',
            name='fechaFin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Fin'),
        ),
    ]
