# Generated by Django 4.2.10 on 2024-05-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tractor', '0004_merge_20240424_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipotractor',
            name='TipoTractor',
            field=models.CharField(max_length=100, verbose_name='Tipo de tractor'),
        ),
    ]
