# Generated by Django 5.0.3 on 2024-04-16 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tractor', '0004_alter_reportetractor_idusuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReporteTractor',
        ),
    ]
