# Generated by Django 4.2.10 on 2024-07-07 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tractor', '0005_alter_tractorsupervisor_fechafin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tractor',
            name='idusuario',
        ),
    ]
