# Generated by Django 4.2.10 on 2024-05-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tractor', '0005_alter_tipotractor_tipotractor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tractor',
            name='horauso',
            field=models.IntegerField(default=0, verbose_name='Hora Uso'),
        ),
    ]
