# Generated by Django 5.0.3 on 2024-04-17 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundo_cultivo', '0001_initial'),
        ('tractor', '0006_reportetractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tractor',
            name='idcultivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fundo_cultivo.cultivo', verbose_name='Cultivo'),
        ),
    ]
