# Generated by Django 4.2.10 on 2024-07-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tractor', '0006_remove_tractor_idusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tractor',
            name='horainicial',
            field=models.IntegerField(verbose_name='Horometro Inicial'),
        ),
    ]
