# Generated by Django 4.2.10 on 2024-04-18 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tractor', '0007_tractor_idcultivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tractor',
            name='nrotractor',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre Tractor'),
        ),
    ]
