# Generated by Django 4.2.10 on 2024-04-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundo_cultivo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variedad',
            name='variedad',
            field=models.CharField(max_length=30, verbose_name='Variedad'),
        ),
    ]
