# Generated by Django 4.2.10 on 2024-04-20 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundo_cultivo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultivo',
            name='idfundo',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='idcultivo',
        ),
        migrations.AddField(
            model_name='lote',
            name='idfundo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fundo_cultivo.fundo', verbose_name='Variedad'),
        ),
        migrations.AddField(
            model_name='variedad',
            name='idcultivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fundo_cultivo.cultivo', verbose_name='Cultivo'),
        ),
    ]
