# Generated by Django 4.2.10 on 2024-05-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundo_cultivo', '0002_alter_variedad_variedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundo',
            name='fundo',
            field=models.CharField(max_length=30, verbose_name='Fundo'),
        ),
    ]
