# Generated by Django 4.2.10 on 2024-04-21 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fundo_cultivo', '0002_alter_cultivo_cultivo_alter_variedad_variedad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultivo',
            name='idfundo',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='idcultivo',
        ),
        migrations.AddField(
            model_name='lote',
            name='idfundo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fundo_cultivo.fundo', verbose_name='Variedad'),
        ),
        migrations.AddField(
            model_name='variedad',
            name='idcultivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fundo_cultivo.cultivo', verbose_name='Cultivo'),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='cultivo',
            field=models.CharField(max_length=30, unique=True, verbose_name='Cultivo'),
        ),
        migrations.AlterField(
            model_name='variedad',
            name='variedad',
            field=models.CharField(max_length=30, unique=True, verbose_name='Variedad'),
        ),
    ]
