# Generated by Django 4.2.10 on 2024-05-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundo_cultivo', '0003_alter_fundo_fundo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivo',
            name='cultivo',
            field=models.CharField(max_length=30, verbose_name='Cultivo'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='lote',
            field=models.CharField(max_length=30, verbose_name='Lote'),
        ),
    ]
