# Generated by Django 5.0.3 on 2024-04-16 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteTractor',
            fields=[
                ('idreportetractor', models.AutoField(primary_key=True, serialize=False)),
                ('horometroinicial', models.IntegerField(verbose_name='Horómetro Inicial')),
                ('horometrofinal', models.IntegerField(verbose_name='Horómetro Final')),
                ('correlativo', models.IntegerField(unique=True, verbose_name='Correlativo')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('idusuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reporte Tractor',
                'verbose_name_plural': 'Reportes Tractores',
            },
        ),
    ]
