# Generated by Django 4.2.10 on 2024-05-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operarios', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposolicitante',
            name='tiposolicitante',
            field=models.CharField(max_length=45, verbose_name='Tipo Solicitante'),
        ),
    ]
