# Generated by Django 5.0.3 on 2024-04-16 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operarios', '0002_reportetractor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReporteTractor',
        ),
    ]
