# Generated by Django 4.2.10 on 2024-06-04 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operarios', '0003_encargado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encargado',
            old_name='persona',
            new_name='idpersona',
        ),
    ]
