# Generated by Django 5.0.3 on 2024-04-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operarios', '0004_solicitante_estado_actividad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tractorista',
            name='codigo',
            field=models.CharField(max_length=12, unique=True, verbose_name='Codigo'),
        ),
    ]
