# Generated by Django 4.2.10 on 2024-04-18 17:06
# 
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operarios', '0004_solicitante_estado_actividad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tractorista',
            name='codigo',
            field=models.CharField(max_length=12, unique=True, verbose_name='Codigo'),
        ),
    ]
