# Generated by Django 4.2.10 on 2024-04-20 23:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_persona'),
        ('operarios', '0005_alter_tractorista_codigo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tractorista',
            options={'ordering': ['idtractorista'], 'verbose_name': 'Tractorista', 'verbose_name_plural': 'Tractoristas'},
        ),
        migrations.RemoveField(
            model_name='solicitante',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='solicitante',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='solicitante',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='tractorista',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='tractorista',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='tractorista',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='tractorista',
            name='nombres',
        ),
        migrations.AddField(
            model_name='solicitante',
            name='actualizado_en',
            field=models.DateField(auto_now=True, verbose_name='Fecha de edición'),
        ),
        migrations.AddField(
            model_name='solicitante',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitante',
            name='idpersona',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='usuario.persona', verbose_name='Persona'),
        ),
        migrations.AddField(
            model_name='tractorista',
            name='actualizado_en',
            field=models.DateField(auto_now=True, verbose_name='Fecha de edición'),
        ),
        migrations.AddField(
            model_name='tractorista',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tractorista',
            name='idpersona',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='usuario.persona', verbose_name='Persona'),
        ),
    ]
