# Generated by Django 4.2.10 on 2024-04-18 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operarios', '0005_alter_tractorista_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tractorista',
            name='idusuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Encargado'),
        ),
    ]
