# Generated by Django 4.2.10 on 2024-04-21 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0002_persona'),
        ('operarios', '0006_alter_tractorista_idusuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tractorista',
            options={'ordering': ['idtractorista'], 'verbose_name': 'Tractorista', 'verbose_name_plural': 'Tractoristas'},
        ),
        migrations.RemoveField(
            model_name='solicitante',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='solicitante',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='solicitante',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='tractorista',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='tractorista',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='tractorista',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='tractorista',
            name='nombres',
        ),
        migrations.AddField(
            model_name='solicitante',
            name='actualizado_en',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha de edición'),
        ),
        migrations.AddField(
            model_name='solicitante',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='solicitante',
            name='idpersona',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='usuario.persona', verbose_name='Persona'),
        ),
        migrations.AddField(
            model_name='tractorista',
            name='actualizado_en',
            field=models.DateField(auto_now=True, verbose_name='Fecha de edición'),
        ),
        migrations.AddField(
            model_name='tractorista',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='tractorista',
            name='idpersona',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='usuario.persona', verbose_name='Persona'),
        ),
        migrations.AlterField(
            model_name='tractorista',
            name='idusuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
