# Generated by Django 4.2.10 on 2024-04-18 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('implemento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='implemento',
            name='horasdeuso',
            field=models.FloatField(default=0, verbose_name='Horas de uso'),
        ),
        migrations.AddField(
            model_name='implemento',
            name='idusuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Encargado'),
        ),
    ]
