# Generated by Django 4.2.10 on 2024-06-03 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('implemento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('componente_pieza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='implemento',
            name='idusuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Encargado'),
        ),
        migrations.AddField(
            model_name='detimplementos',
            name='iddetallecomponente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='componente_pieza.detallecomponente', verbose_name='Detalle componente'),
        ),
        migrations.AddField(
            model_name='detimplementos',
            name='idimplemento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='implemento.implemento', verbose_name='Implemento'),
        ),
    ]
