# Generated by Django 4.2.10 on 2024-06-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implemento', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='implemento',
            name='mantenimientos',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Mantenimientos realizados'),
        ),
    ]
