# Generated by Django 4.2.10 on 2024-05-17 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('implemento', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipoimplemento',
            old_name='configuracion_implemento',
            new_name='idconfiguracion_implemento',
        ),
    ]
