# Generated by Django 4.2.10 on 2024-04-25 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('componente_pieza', '0001_initial'),
        ('implemento', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detimplementos',
            name='sistema',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='componente_pieza.sistema', verbose_name='Sistema'),
        ),
    ]
