# Generated by Django 4.2.10 on 2024-04-21 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_persona'),
        ('ceco', '0001_initial'),
        ('implemento', '0003_implemento_estado_actividad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detimplementos',
            options={'ordering': ['idpieza', 'creado_en'], 'verbose_name': 'Detalle Implemento', 'verbose_name_plural': 'Detalle Implementos'},
        ),
        migrations.RemoveField(
            model_name='detimplementos',
            name='idceco',
        ),
        migrations.RemoveField(
            model_name='detimplementos',
            name='idresponsable',
        ),
        migrations.RemoveField(
            model_name='implemento',
            name='nroimplemento',
        ),
        migrations.AddField(
            model_name='detimplementos',
            name='idpersona',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='usuario.persona', verbose_name='Persona'),
        ),
        migrations.AddField(
            model_name='implemento',
            name='idceco',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='ceco.ceco', verbose_name='Ceco'),
        ),
    ]
