# Generated by Django 4.2.10 on 2024-05-22 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('componente_pieza', '0004_alter_dettaleconfiguracion_options'),
        ('implemento', '0003_rename_configuracion_implemento_tipoimplemento_idconfiguracion_implemento'),
    ]

    operations = [
        migrations.AddField(
            model_name='detimplementos',
            name='CRcomponente',
            field=models.IntegerField(default=0, verbose_name='Cambios realizados al componente'),
        ),
        migrations.AddField(
            model_name='detimplementos',
            name='CRpieza',
            field=models.IntegerField(default=0, verbose_name='Cambios realizados a la pieza'),
        ),
        migrations.AddField(
            model_name='detimplementos',
            name='HUcomponente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Horas de uso del componente'),
        ),
        migrations.AddField(
            model_name='detimplementos',
            name='HUpieza',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Horas de uso de la pieza'),
        ),
        migrations.AddField(
            model_name='detimplementos',
            name='MRcomponente',
            field=models.IntegerField(default=0, verbose_name='Mantenimientos realizados al componente'),
        ),
        migrations.AddField(
            model_name='detimplementos',
            name='MRimplemento',
            field=models.IntegerField(default=0, verbose_name='Mantenimientos realizados al implemento'),
        ),
        migrations.AddField(
            model_name='detimplementos',
            name='MRpieza',
            field=models.IntegerField(default=0, verbose_name='Mantenimientos realizados a la pieza'),
        ),
        migrations.AddField(
            model_name='detimplementos',
            name='cantidadpieza',
            field=models.IntegerField(default=0, verbose_name='Cantidad de piezas'),
        ),
        migrations.AddField(
            model_name='detimplementos',
            name='idcomponente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='componente_pieza.componente', verbose_name='Componente'),
        ),
        migrations.AddField(
            model_name='detimplementos',
            name='idpieza',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='componente_pieza.pieza', verbose_name='Pieza'),
        ),
    ]
