# Generated by Django 4.2.10 on 2024-06-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implemento', '0003_implemento_mantenimientos'),
    ]

    operations = [
        migrations.AddField(
            model_name='implemento',
            name='proximo_mantenimiento',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Proximo Mantenimiento'),
        ),
    ]
