# Generated by Django 4.2.10 on 2024-04-25 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('implemento', '0004_alter_detimplementos_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detimplementos',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='detimplementos',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='detimplementos',
            name='idceco',
        ),
        migrations.RemoveField(
            model_name='detimplementos',
            name='idpersona',
        ),
    ]
