# Generated by Django 4.2.10 on 2024-06-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implemento', '0005_implementosupervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implementosupervisor',
            name='fechaInicio',
            field=models.DateField(verbose_name='Fecha Inicio'),
        ),
    ]
