# Generated by Django 4.2.10 on 2024-04-26 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('componente_pieza', '0004_pieza'),
        ('implemento', '0005_remove_detimplementos_actualizado_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detimplementos',
            name='sistema',
        ),
        migrations.AddField(
            model_name='detimplementos',
            name='idcomponente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='componente_pieza.componente', verbose_name='Componente'),
        ),
    ]
