# Generated by Django 4.2.10 on 2024-05-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implemento', '0006_remove_detimplementos_sistema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoimplemento',
            name='tipoimplemento',
            field=models.CharField(max_length=45, verbose_name='Tipo Implemento'),
        ),
    ]
