# Generated by Django 4.2.10 on 2024-06-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implemento', '0006_alter_implementosupervisor_fechainicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implementosupervisor',
            name='fechaFin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Fin'),
        ),
    ]
