# Generated by Django 4.2.10 on 2024-07-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implemento', '0007_alter_implementosupervisor_fechafin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implemento',
            name='horasdeuso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Horas de uso'),
        ),
    ]
