# Generated by Django 4.2.10 on 2024-07-07 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('implemento', '0009_alter_implemento_idusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='implemento',
            name='idusuario',
        ),
    ]
