# Generated by Django 4.2.10 on 2024-04-24 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localizacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='sede',
            field=models.CharField(max_length=50, unique=True, verbose_name='Sede'),
        ),
    ]
