# Generated by Django 4.2.10 on 2024-05-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localizacion', '0002_alter_sede_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='sede',
            field=models.CharField(max_length=50, verbose_name='Sede'),
        ),
    ]
