# Generated by Django 4.2.10 on 2024-05-25 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operarios', '0001_initial'),
        ('fundo_cultivo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleLabor',
            fields=[
                ('iddetlabor', models.AutoField(primary_key=True, serialize=False)),
                ('horadeuso', models.IntegerField(null=True, verbose_name='Hora de uso Implemento')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Detalle Labor',
                'verbose_name_plural': 'Detalles de labor',
            },
        ),
        migrations.CreateModel(
            name='TipoLabor',
            fields=[
                ('idtipolabor', models.AutoField(primary_key=True, serialize=False)),
                ('tipolabor', models.CharField(max_length=30, unique=True, verbose_name='Tipo de labor')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Tipo de labor',
                'verbose_name_plural': 'Tipos de labor',
            },
        ),
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('idprogramacion', models.AutoField(primary_key=True, serialize=False)),
                ('fechahora', models.DateField(verbose_name='Fecha')),
                ('turno', models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde')], max_length=1, verbose_name='Turno')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('idlote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fundo_cultivo.lote', verbose_name='Lote')),
                ('idsolicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operarios.solicitante', verbose_name='Solicitante')),
                ('idtipolabor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programacion_labor.tipolabor', verbose_name='Tipo de labor')),
            ],
            options={
                'verbose_name': 'Programacion',
                'verbose_name_plural': 'Programaciones',
            },
        ),
    ]
