<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 4.2.10 on 2024-04-09 21:57
=======
# Generated by Django 4.2.10 on 2024-04-10 23:56
>>>>>>> Backend-Harold

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 5.0.3 on 2024-04-11 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
>>>>>>> BackEnd-Fabian


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
<<<<<<< HEAD
        ('tractor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fundo_cultivo', '0001_initial'),
        ('implemento', '0001_initial'),
=======
        ('implemento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fundo_cultivo', '0001_initial'),
        ('tractor', '0001_initial'),
>>>>>>> Backend-Harold
        ('operarios', '0001_initial'),
=======
        ('fundo_cultivo', '0001_initial'),
        ('implemento', '0001_initial'),
        ('operarios', '0001_initial'),
        ('tractor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> BackEnd-Fabian
    ]

    operations = [
        migrations.CreateModel(
            name='TipoLabor',
            fields=[
                ('idtipolabor', models.AutoField(primary_key=True, serialize=False)),
                ('tipolabor', models.CharField(max_length=30, unique=True, verbose_name='Tipo de labor')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Tipo de labor',
                'verbose_name_plural': 'Tipos de labor',
            },
        ),
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('idprogramacion', models.AutoField(primary_key=True, serialize=False)),
                ('fechahora', models.DateField(verbose_name='Fecha')),
                ('turno', models.CharField(choices=[('M', 'Manana'), ('T', 'Tarde'), ('N', 'Noche')], max_length=1, verbose_name='Turno')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('idlote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fundo_cultivo.lote', verbose_name='Lote')),
                ('idsolicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operarios.solicitante', verbose_name='Solicitante')),
<<<<<<< HEAD
                ('idtipolabor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programacion_labor.tipolabor', verbose_name='Tipo de labor')),
                ('idtractor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tractor.tractor', verbose_name='Tractor')),
                ('idtractorista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operarios.tractorista', verbose_name='Tractorista')),
                ('idusuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
=======
                ('idtractor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tractor.tractor', verbose_name='Tractor')),
                ('idtractorista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operarios.tractorista', verbose_name='Tractorista')),
                ('idusuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('idtipolabor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programacion_labor.tipolabor', verbose_name='Tipo de labor')),
>>>>>>> BackEnd-Fabian
            ],
            options={
                'verbose_name': 'Programacion',
                'verbose_name_plural': 'Programaciones',
            },
        ),
        migrations.CreateModel(
            name='DetalleLabor',
            fields=[
                ('iddetlabor', models.AutoField(primary_key=True, serialize=False)),
                ('horadeuso', models.TimeField(verbose_name='Hora de uso Implemento')),
                ('idimplemento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='implemento.implemento', verbose_name='Implemento')),
                ('idprogramacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programacion_labor.programacion', verbose_name='Programacion')),
            ],
        ),
    ]
