# Generated by Django 4.2.10 on 2024-04-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion_labor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallelabor',
            options={'verbose_name': 'Detalle Labor', 'verbose_name_plural': 'Detalles de labor'},
        ),
        migrations.AddField(
            model_name='detallelabor',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='programacion',
            name='turno',
            field=models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde'), ('N', 'Noche')], max_length=1, verbose_name='Turno'),
        ),
    ]
