# Generated by Django 4.2.10 on 2024-04-13 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('implemento', '0001_initial'),
        ('programacion_labor', '0002_alter_detallelabor_options_detallelabor_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleProgramacion',
            fields=[
                ('iddetalleprogramacion', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('implemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_programacion', to='implemento.implemento')),
                ('programacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_programacion', to='programacion_labor.programacion')),
            ],
            options={
                'verbose_name': 'Detalle de Programacion',
                'verbose_name_plural': 'Detalles de Programacion',
            },
        ),
        migrations.AddField(
            model_name='programacion',
            name='implementos',
            field=models.ManyToManyField(through='programacion_labor.DetalleProgramacion', to='implemento.implemento', verbose_name='Implementos'),
        ),
    ]
