# Generated by Django 4.2.10 on 2024-04-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion_labor', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallelabor',
            name='horadeuso',
            field=models.IntegerField(verbose_name='Hora de uso Implemento'),
        ),
    ]
