# Generated by Django 4.2.10 on 2024-04-13 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programacion_labor', '0003_detalleprogramacion_programacion_implementos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programacion',
            name='implementos',
        ),
        migrations.DeleteModel(
            name='DetalleProgramacion',
        ),
    ]
