# Generated by Django 5.0.3 on 2024-04-16 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programacion_labor', '0004_reportetractor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReporteTractor',
        ),
    ]
