# Generated by Django 4.2.10 on 2024-07-01 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('implemento', '0007_alter_implementosupervisor_fechafin'),
        ('tractor', '0005_alter_tractorsupervisor_fechafin'),
        ('programacion_labor', '0004_alter_programacion_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallelabor',
            name='idimplemento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='implemento.implementosupervisor', verbose_name='Implemento'),
        ),
        migrations.AlterField(
            model_name='programacion',
            name='idtractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tractor.tractorsupervisor', verbose_name='Tractor'),
        ),
    ]
