# Generated by Django 4.2.10 on 2024-04-17 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programacion_labor', '0004_alter_detallelabor_horadeuso'),
        ('programacion_labor', '0005_delete_reportetractor'),
    ]

    operations = [
    ]
