# Generated by Django 4.2.10 on 2024-04-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion_labor', '0006_merge_20240417_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallelabor',
            name='horadeuso',
            field=models.IntegerField(null=True, verbose_name='Hora de uso Implemento'),
        ),
    ]
