# Generated by Django 4.2.10 on 2024-04-21 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('implemento', '0004_alter_detimplementos_options_and_more'),
        ('ceco', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Responsable',
        ),
    ]
