# Generated by Django 4.2.10 on 2024-04-25 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('implemento', '0003_detimplementos_sistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='MantenimientoPreventivo',
            fields=[
                ('idmantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fechaprogramacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Programacion')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('detimplemento', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='implemento.detimplementos', verbose_name='Detimplement')),
            ],
        ),
    ]
