# Generated by Django 4.2.10 on 2024-06-03 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('implemento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acciones',
            fields=[
                ('idaccion', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=45, unique=True, verbose_name='Acción de mantenimiento')),
                ('estado', models.IntegerField(choices=[(0, 'Supervisor'), (1, 'Mecánico'), (2, 'Ambos')], verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Acción',
                'verbose_name_plural': 'Acciones',
            },
        ),
        migrations.CreateModel(
            name='DetalleCambios',
            fields=[
                ('iddetallecambio', models.AutoField(primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Detalle Cambio',
                'verbose_name_plural': 'Detalles de Cambios',
            },
        ),
        migrations.CreateModel(
            name='DetalleMantenimiento',
            fields=[
                ('iddetallemantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('completado', models.CharField(max_length=2, verbose_name='Completado')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Detalle Mantenimiento',
                'verbose_name_plural': 'Detalles de Mantenimientos',
            },
        ),
        migrations.CreateModel(
            name='DetMotivos',
            fields=[
                ('iddetmotivo', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Motivo',
                'verbose_name_plural': 'Motivos',
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('iddiagnostico', models.AutoField(primary_key=True, serialize=False)),
                ('diagnostico', models.CharField(max_length=45, verbose_name='Diagnostico')),
                ('det', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Diagnostico',
                'verbose_name_plural': 'Diagnosticos',
            },
        ),
        migrations.CreateModel(
            name='ProgramacionMantenimiento',
            fields=[
                ('idprogramacionmantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fechaprogramacion', models.DateField(blank=True, null=True, verbose_name='Fecha mantenimiento')),
                ('tipomantenimiento', models.IntegerField(blank=True, choices=[(1, 'Preventivo'), (0, 'Correctvo')], null=True, verbose_name='Tipo mantenimiento')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('idimplemento', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='implemento.implemento', verbose_name='Implemento')),
            ],
            options={
                'verbose_name': 'Programacion Mantenimiento',
                'verbose_name_plural': 'Programacion de Mantenimientos',
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('idmantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fechaingreso', models.DateField(blank=True, null=True, verbose_name='Fecha Ingreso')),
                ('fechasalida', models.DateField(blank=True, null=True, verbose_name='Fecha Fecha Salida')),
                ('descripcion', models.CharField(max_length=45, verbose_name='Descripcion')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('idprogramacionmantenimiento', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='mantenimiento.programacionmantenimiento', verbose_name='Programacion')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
            },
        ),
    ]
