# Generated by Django 4.2.10 on 2024-05-17 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('implemento', '0002_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('iddiagnostico', models.AutoField(primary_key=True, serialize=False)),
                ('diagnostico', models.CharField(max_length=45, verbose_name='Diagnostico')),
                ('det', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramacionMantenimiento',
            fields=[
                ('idprogramacionmantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fechaprogramacion', models.DateField(verbose_name='Fecha Fecha Salida')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('idimplemento', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='implemento.implemento', verbose_name='Implemento')),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('idmantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipomantenimiento', models.CharField(max_length=45, verbose_name='Tipo mantenimiento')),
                ('fechaingreso', models.DateField(verbose_name='Fecha Ingreso')),
                ('fechasalida', models.DateField(verbose_name='Fecha Fecha Salida')),
                ('descripcion', models.CharField(max_length=45, verbose_name='Descripcion')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('persona', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='usuario.persona', verbose_name='Persona')),
            ],
        ),
    ]
