# Generated by Django 4.2.10 on 2024-06-03 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('mantenimiento', '0001_initial'),
        ('implemento', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='persona',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='usuario.persona', verbose_name='Persona'),
        ),
        migrations.AddField(
            model_name='detmotivos',
            name='idaccion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='mantenimiento.acciones', verbose_name='Accion'),
        ),
        migrations.AddField(
            model_name='detmotivos',
            name='idprogramacionmantenimiento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='mantenimiento.programacionmantenimiento', verbose_name='Programacion de Mantenmiento'),
        ),
        migrations.AddField(
            model_name='detallemantenimiento',
            name='idaccion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='mantenimiento.acciones', verbose_name='Accion'),
        ),
        migrations.AddField(
            model_name='detallemantenimiento',
            name='idmantenimiento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='mantenimiento.mantenimiento', verbose_name='Mantenimiento'),
        ),
        migrations.AddField(
            model_name='detallecambios',
            name='iddetalleimplemento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='implemento.detimplementos', verbose_name='Mantenimiento'),
        ),
        migrations.AddField(
            model_name='detallecambios',
            name='idmantenimiento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='mantenimiento.mantenimiento', verbose_name='Mantenimiento'),
        ),
    ]
