# Generated by Django 4.2.10 on 2024-05-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacionmantenimiento',
            name='fechaprogramacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha mantenimiento'),
        ),
    ]
