# Generated by Django 4.2.10 on 2024-04-25 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_persona_dni'),
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mantenimientopreventivo',
            options={'verbose_name': 'Mantenimiento Preventivo', 'verbose_name_plural': 'Mantenimientos Preventivos'},
        ),
        migrations.RenameField(
            model_name='mantenimientopreventivo',
            old_name='idmantenimiento',
            new_name='idmanpreventivo',
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('idmantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fechasalida', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('descripcion', models.CharField(max_length=60, verbose_name='Descripcion')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('idmanpreventivo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='mantenimiento.mantenimientopreventivo', verbose_name='mantenimiento preventivo')),
                ('idpersona', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='usuario.persona', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
            },
        ),
    ]
