# Generated by Django 4.2.10 on 2024-04-25 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('implemento', '0004_alter_detimplementos_options_and_more'),
        ('mantenimiento', '0002_alter_mantenimientopreventivo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientopreventivo',
            name='detimplemento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='implemento.detimplementos', verbose_name='Detimplemento'),
        ),
        migrations.AlterField(
            model_name='mantenimientopreventivo',
            name='fechaprogramacion',
            field=models.DateField(verbose_name='Fecha Programacion'),
        ),
    ]
