# Generated by Django 4.2.10 on 2024-05-26 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='idprogramacionmantenimiento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='mantenimiento.programacionmantenimiento', verbose_name='Programacion'),
        ),
    ]
