# Generated by Django 4.2.10 on 2024-06-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0003_recambios_remove_detallemantenimiento_completado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallemantenimiento',
            name='Realizado',
        ),
        migrations.AddField(
            model_name='detallemantenimiento',
            name='completado',
            field=models.BooleanField(default=True, verbose_name='Realizado'),
        ),
    ]
