# Generated by Django 4.2.10 on 2024-04-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0003_alter_mantenimientopreventivo_detimplemento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientopreventivo',
            name='fechaprogramacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Programacion'),
        ),
    ]
