# Generated by Django 4.2.10 on 2024-05-26 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('mantenimiento', '0003_mantenimiento_idprogramacionmantenimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='fechaingreso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Ingreso'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fechasalida',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Fecha Salida'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='persona',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='usuario.persona', verbose_name='Persona'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='tipomantenimiento',
            field=models.CharField(blank=True, choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctvo')], max_length=45, null=True, verbose_name='Tipo mantenimiento'),
        ),
    ]
