# Generated by Django 4.2.10 on 2024-04-26 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('implemento', '0006_remove_detimplementos_sistema_and_more'),
        ('componente_pieza', '0004_pieza'),
        ('mantenimiento', '0004_alter_mantenimientopreventivo_fechaprogramacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleDiagnostico',
            fields=[
                ('iddetallediagnostico', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=45, verbose_name='Motivo')),
                ('sugerencia', models.CharField(max_length=45, verbose_name='Sugerencia')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('iddiagnostico', models.AutoField(primary_key=True, serialize=False)),
                ('diagnostico', models.CharField(max_length=60, verbose_name='Diagnostico')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Diagnostico',
                'verbose_name_plural': 'Diagnosticos',
            },
        ),
        migrations.CreateModel(
            name='ProgramacionMatenimiento',
            fields=[
                ('idprogramacionmantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fechaprogramacion', models.DateField(blank=True, null=True, verbose_name='Fecha Programacion')),
                ('contadormantenimiento', models.IntegerField(verbose_name='Contador Mantenimiento')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('detimplemento', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='implemento.detimplementos', verbose_name='Detimplemento')),
            ],
            options={
                'verbose_name': 'Porgramacion Mantenimiento',
                'verbose_name_plural': 'Programaciones Mantenimientos',
            },
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='idmanpreventivo',
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='fechaingreso',
            field=models.DateField(null=True, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='tipomantenimiento',
            field=models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo')], default='preventivo', max_length=20, verbose_name='Tipo de mantenimiento'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fechasalida',
            field=models.DateField(null=True, verbose_name='Fecha de Salida'),
        ),
        migrations.DeleteModel(
            name='MantenimientoPreventivo',
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='idmantenimiento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='mantenimiento.mantenimiento', verbose_name='idmantenimiento'),
        ),
        migrations.AddField(
            model_name='detallediagnostico',
            name='iddiagnostico',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='mantenimiento.diagnostico', verbose_name='idiagnostico'),
        ),
        migrations.AddField(
            model_name='detallediagnostico',
            name='idpieza',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='componente_pieza.pieza', verbose_name='Pieza'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='idprogramacionmantenimiento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='mantenimiento.programacionmatenimiento', verbose_name='Programacion mantenimiento'),
        ),
    ]
