# Generated by Django 4.2.10 on 2024-06-03 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0004_remove_detallemantenimiento_realizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recambios',
            name='idmantenimiento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='mantenimiento.mantenimiento', verbose_name='Mantenimiento'),
        ),
    ]
