# Generated by Django 4.2.10 on 2024-05-28 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0004_alter_mantenimiento_fechaingreso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acciones',
            fields=[
                ('idaccion', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=45, unique=True, verbose_name='Accion de mantenimiento')),
                ('estado', models.CharField(max_length=15, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Accion',
                'verbose_name_plural': 'Acciones',
            },
        ),
        migrations.CreateModel(
            name='DetMotivos',
            fields=[
                ('iddetmotivo', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idaccion', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='mantenimiento.acciones', verbose_name='Accion')),
                ('idprogramacionmantenimiento', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='mantenimiento.programacionmantenimiento', verbose_name='Programacion de Mantenmiento')),
            ],
            options={
                'verbose_name': 'Motivo',
                'verbose_name_plural': 'Motivos',
            },
        ),
    ]
