# Generated by Django 4.2.10 on 2024-05-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0005_acciones_detmotivos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acciones',
            options={'verbose_name': 'Acción', 'verbose_name_plural': 'Acciones'},
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='tipomantenimiento',
        ),
        migrations.AddField(
            model_name='programacionmantenimiento',
            name='tipomantenimiento',
            field=models.CharField(blank=True, choices=[(1, 'Preventivo'), (0, 'Correctvo')], max_length=10, null=True, verbose_name='Tipo mantenimiento'),
        ),
        migrations.AlterField(
            model_name='acciones',
            name='accion',
            field=models.CharField(max_length=45, unique=True, verbose_name='Acción de mantenimiento'),
        ),
        migrations.AlterField(
            model_name='acciones',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Supervisor'), (1, 'Mecánico'), (2, 'Ambos')], verbose_name='Rol'),
        ),
    ]
