# Generated by Django 4.2.10 on 2024-04-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0005_detallediagnostico_diagnostico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='fechaingreso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fechasalida',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Salida'),
        ),
    ]
