# Generated by Django 4.2.10 on 2024-06-04 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operarios', '0003_encargado'),
        ('mantenimiento', '0005_recambios_idmantenimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='persona',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='operarios.encargado', verbose_name='Persona'),
        ),
    ]
