# Generated by Django 4.2.10 on 2024-05-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0006_alter_acciones_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacionmantenimiento',
            name='tipomantenimiento',
            field=models.IntegerField(blank=True, choices=[(1, 'Preventivo'), (0, 'Correctvo')], null=True, verbose_name='Tipo mantenimiento'),
        ),
    ]
