# Generated by Django 4.2.10 on 2024-06-04 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operarios', '0004_rename_persona_encargado_idpersona'),
        ('mantenimiento', '0006_alter_mantenimiento_persona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimiento',
            name='persona',
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='idencargado',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='operarios.encargado', verbose_name='Encargado'),
        ),
    ]
