# Generated by Django 4.2.10 on 2024-06-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0007_remove_mantenimiento_persona_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacionmantenimiento',
            name='estado_mantenimiento',
            field=models.IntegerField(blank=True, choices=[(0, 'Programado'), (1, 'Aceptado'), (2, 'Finalizado')], null=True, verbose_name='Estado del Mantenimiento'),
        ),
    ]
