# Generated by Django 4.2.10 on 2024-05-30 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('implemento', '0002_initial'),
        ('mantenimiento', '0007_alter_programacionmantenimiento_tipomantenimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleMantenimiento',
            fields=[
                ('iddetallemantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('completado', models.CharField(max_length=2, verbose_name='Completado')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('idaccion', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='mantenimiento.acciones', verbose_name='Accion')),
                ('idmantenimiento', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='mantenimiento.mantenimiento', verbose_name='Mantenimiento')),
            ],
            options={
                'verbose_name': 'Detalle Mantenimiento',
                'verbose_name_plural': 'Detalles de Mantenimientos',
            },
        ),
        migrations.CreateModel(
            name='DetalleCambios',
            fields=[
                ('iddetallecambio', models.AutoField(primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('iddetalleimplemento', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='implemento.detimplementos', verbose_name='Mantenimiento')),
                ('idmantenimiento', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='mantenimiento.mantenimiento', verbose_name='Mantenimiento')),
            ],
            options={
                'verbose_name': 'Detalle Cambio',
                'verbose_name_plural': 'Detalles de Cambios',
            },
        ),
    ]
