# Generated by Django 4.2.10 on 2024-06-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0008_programacionmantenimiento_estado_mantenimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacionmantenimiento',
            name='estado_mantenimiento',
            field=models.IntegerField(blank=True, choices=[(0, 'Programado'), (1, 'Aceptado'), (2, 'Finalizado')], default=0, null=True, verbose_name='Estado del Mantenimiento'),
        ),
    ]
