# Generated by Django 4.2.10 on 2024-07-02 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('implemento', '0007_alter_implementosupervisor_fechafin'),
        ('mantenimiento', '0009_alter_programacionmantenimiento_estado_mantenimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacionmantenimiento',
            name='idimplemento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='implemento.implementosupervisor', verbose_name='Implemento'),
        ),
    ]
