# Generated by Django 4.2.10 on 2024-07-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0010_alter_programacionmantenimiento_idimplemento'),
    ]

    operations = [
        migrations.AddField(
            model_name='acciones',
            name='estado_actividad',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Estado'),
        ),
    ]
