# Generated by Django 4.2.10 on 2024-04-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idpersona', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=45, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=45, verbose_name='Apellidos')),
                ('direccion', models.CharField(max_length=45, verbose_name='Direccion')),
                ('dni', models.CharField(max_length=8, null=True, verbose_name='DNI')),
                ('codigo', models.CharField(max_length=12, null=True, verbose_name='Codigo')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
    ]
