# Generated by Django 4.2.10 on 2024-05-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_persona_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='DNI'),
        ),
    ]
