# Generated by Django 4.2.10 on 2024-04-09 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('idcomponente', models.AutoField(primary_key=True, serialize=False)),
                ('componente', models.CharField(max_length=45, verbose_name='Componente')),
                ('codcomponente', models.CharField(max_length=12, verbose_name='Código componente')),
                ('horainstalacion', models.IntegerField(verbose_name='Hora Instalacion')),
                ('tiempovida', models.IntegerField(verbose_name='Tiempo de vida')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componentes',
                'ordering': ['componente', 'idsistema'],
            },
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('idsistema', models.AutoField(primary_key=True, serialize=False)),
                ('sistema', models.CharField(max_length=45, unique=True, verbose_name='Sistema')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Sistema',
                'verbose_name_plural': 'Sistemas',
                'ordering': ['sistema'],
            },
        ),
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('idpieza', models.AutoField(primary_key=True, serialize=False)),
                ('pieza', models.CharField(max_length=45, verbose_name='Pieza')),
                ('codpieza', models.CharField(max_length=12, verbose_name='Codigo de pieza')),
                ('tiempoinstalacion', models.IntegerField(verbose_name='Tiempo de instalacion')),
                ('tiempovida', models.IntegerField(verbose_name='Tiempo de vida')),
                ('frecuenciaMP', models.IntegerField(verbose_name='Frecuencia de mantenimiento de pieza')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateField(auto_now=True, verbose_name='Fecha de edición')),
                ('idcomponente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='componente_pieza.componente', verbose_name='Componenete')),
            ],
            options={
                'verbose_name': 'Pieza',
                'verbose_name_plural': 'Piezas',
                'ordering': ['pieza', 'idcomponente'],
            },
        ),
        migrations.AddField(
            model_name='componente',
            name='idsistema',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='componente_pieza.sistema', verbose_name='Sistema'),
        ),
    ]
