# Generated by Django 4.2.10 on 2024-05-21 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('componente_pieza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleComponente',
            fields=[
                ('iddetallecomponente', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(verbose_name='Cantidad de Piezas')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('idcomponente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='componente_pieza.componente', verbose_name='Componente')),
                ('idpieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='componente_pieza.pieza', verbose_name='Pieza')),
            ],
            options={
                'verbose_name': 'Detalles Componente',
                'verbose_name_plural': 'Detalles Componentes',
            },
        ),
    ]
