# Generated by Django 4.2.10 on 2024-04-25 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('implemento', '0004_alter_detimplementos_options_and_more'),
        ('componente_pieza', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componente',
            options={'ordering': ['componente'], 'verbose_name': 'Componente', 'verbose_name_plural': 'Componentes'},
        ),
        migrations.RemoveField(
            model_name='componente',
            name='horainstalacion',
        ),
        migrations.AlterField(
            model_name='componente',
            name='idsistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='componente_pieza.sistema', verbose_name='Sistema'),
        ),
        migrations.DeleteModel(
            name='Pieza',
        ),
    ]
