# Generated by Django 4.2.10 on 2024-05-25 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('componente_pieza', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pieza',
            name='cantidad_piezas',
        ),
    ]
