# Generated by Django 4.2.10 on 2024-05-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componente_pieza', '0002_detallecomponente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pieza',
            name='idcomponente',
        ),
        migrations.AlterField(
            model_name='pieza',
            name='frecuencia_man',
            field=models.IntegerField(verbose_name='Frecuencia de mantenimiento'),
        ),
        migrations.AlterField(
            model_name='pieza',
            name='tiempovida',
            field=models.IntegerField(verbose_name='Tiempo de vida'),
        ),
    ]
