# Generated by Django 4.2.10 on 2024-07-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componente_pieza', '0002_alter_sistema_sistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='codcomponente',
            field=models.CharField(max_length=12, verbose_name='Código componente'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='componente',
            field=models.CharField(max_length=45, verbose_name='Componente'),
        ),
    ]
