# Generated by Django 4.2.10 on 2024-05-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componente_pieza', '0002_remove_pieza_cantidad_piezas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DettaleConfiguracion',
            new_name='DetalleConfiguracion',
        ),
        migrations.AlterField(
            model_name='detallecomponente',
            name='cantidad',
            field=models.IntegerField(default=1, verbose_name='Cantidad de Piezas'),
        ),
    ]
