# Generated by Django 4.2.10 on 2024-05-22 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('componente_pieza', '0003_remove_pieza_idcomponente_alter_pieza_frecuencia_man_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dettaleconfiguracion',
            options={'verbose_name': 'Detalles de Configuracion', 'verbose_name_plural': 'Detalles de configuraciones'},
        ),
    ]
