# Generated by Django 4.2.10 on 2024-04-26 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('componente_pieza', '0003_componente_frecuencia_man'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('idpieza', models.AutoField(primary_key=True, serialize=False)),
                ('pieza', models.CharField(max_length=45, verbose_name='Pieza')),
                ('codpieza', models.CharField(max_length=12, verbose_name='Codigo de pieza')),
                ('tiempoinstalacion', models.IntegerField(verbose_name='Tiempo de instalacion')),
                ('tiempovida', models.IntegerField(verbose_name='Tiempo de vida')),
                ('frecuenciaMP', models.IntegerField(verbose_name='Frecuencia de mantenimiento de pieza')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateField(auto_now=True, verbose_name='Fecha de edición')),
                ('idcomponente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='componente_pieza.componente', verbose_name='Componenete')),
            ],
            options={
                'verbose_name': 'Pieza',
                'verbose_name_plural': 'Piezas',
                'ordering': ['pieza', 'idcomponente'],
            },
        ),
    ]
