# Generated by Django 4.2.10 on 2024-05-23 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('componente_pieza', '0003_remove_pieza_idcomponente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dettaleconfiguracion',
            options={'verbose_name': 'Detalles Configuracion', 'verbose_name_plural': 'Detalles Configuraciones'},
        ),
    ]
